/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health of the app
         * @description 200 when the app and its Redis work, 503 with the same body when Redis does not.
         *
         *     The body is compact JSON: deploy checks look for `"version":"<version>"` and the commit.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health of the data sources
         * @description Reachability of Binance (`GET /api/v3/ping`) and Alpaca (`GET /v2/clock`), checked at
         *     most once a minute. 200 when both answer, 503 with the same body when one does not.
         */
        get: operations["sources_health_api_health_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candles
         * @description Closed candles of one instrument and timeframe with `start <= t < end`.
         *
         *     Stocks have regular-session candles only (09:30-16:00 New York), aligned to the session
         *     open. Missing candles are never filled; `meta.gaps` reports them. Limits: `max_candles`
         *     expected candles per request (see the instrument detail) and a per-minute number of
         *     candle and instrument requests per client address.
         */
        get: operations["candles_api_v1_data_candles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search instruments
         * @description Searches the instruments of both markets: every Binance spot pair that is trading and
         *     every active tradable US stock and ETF at Alpaca (without OTC).
         *
         *     Ranking: the top pair of a crypto base asset equal to the query (`btc` finds `BTCUSDT`
         *     first), exact symbol, the other pairs of that base asset, symbol prefix, prefix of a word
         *     in the name, substring of the symbol, substring of the name; ties go to the shorter symbol,
         *     then alphabetically.
         *
         *     When the instrument list of one market cannot be loaded, the other market is still
         *     searched and `unavailable` names the missing one; 503 when no market can be searched.
         */
        get: operations["search_instruments_api_v1_data_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Instrument detail
         * @description An instrument with its timeframes, available period and the candle limit: what a valid
         *     `/candles` request can ask for. Counts against the per-minute limit of requests per client
         *     address, like `/candles`.
         */
        get: operations["instrument_detail_api_v1_data_instruments__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandlesMeta */
        CandlesMeta: {
            /**
             * Count
             * @description Number of candles returned.
             * @example 3
             */
            count: number;
            /**
             * End
             * @description End of the period (exclusive), UTC epoch seconds.
             * @example 1717214400
             */
            end: number;
            /**
             * Feed
             * @example spot
             * @enum {string}
             */
            feed: "spot" | "iex";
            /**
             * Fingerprint
             * @description `sha256:<hex>` over the request and its candles: the same candles give the same value, any changed number another.
             * @example sha256:3b1f0c9e5d7a4b2c8e6f1a0d9c7b5e3f2a4c6e8d0b1f3a5c7e9d2b4f6a8c0e1d
             */
            fingerprint: string;
            /**
             * Gaps
             * @description Missing candles as merged `[start, end)` ranges in UTC epoch seconds, earliest first, at most 100.
             * @example [
             *       [
             *         1717207200,
             *         1717210800
             *       ]
             *     ]
             */
            gaps: [
                number,
                number
            ][];
            /**
             * Gaps Total
             * @description Number of missing candles in total.
             * @example 1
             */
            gaps_total: number;
            /**
             * Instrument
             * @description Instrument id, normalised.
             * @example crypto:BTCUSDT
             */
            instrument: string;
            /**
             * Source
             * @example binance
             * @enum {string}
             */
            source: "binance" | "alpaca";
            /**
             * Start
             * @description Start of the period (inclusive), UTC epoch seconds.
             * @example 1717200000
             */
            start: number;
            /** @example 1h */
            timeframe: components["schemas"]["Timeframe"];
        };
        /**
         * CandlesOut
         * @description Candles as columns: index `i` of every array is one candle, oldest first.
         */
        CandlesOut: {
            /**
             * C
             * @description Close prices.
             * @example [
             *       67612.4,
             *       67540.3,
             *       67601.9
             *     ]
             */
            c: number[];
            /**
             * H
             * @description High prices.
             * @example [
             *       67700,
             *       67650,
             *       67640
             *     ]
             */
            h: number[];
            /**
             * L
             * @description Low prices.
             * @example [
             *       67420.2,
             *       67510,
             *       67488.8
             *     ]
             */
            l: number[];
            meta: components["schemas"]["CandlesMeta"];
            /**
             * O
             * @description Open prices.
             * @example [
             *       67491,
             *       67612.5,
             *       67580.1
             *     ]
             */
            o: number[];
            /**
             * T
             * @description Open times, UTC epoch seconds, strictly increasing.
             * @example [
             *       1717200000,
             *       1717203600,
             *       1717210800
             *     ]
             */
            t: number[];
            /**
             * V
             * @description Volumes: base asset for crypto, shares (IEX only) for stocks.
             * @example [
             *       512.31,
             *       398.07,
             *       421.55
             *     ]
             */
            v: number[];
        };
        /** Health */
        Health: {
            /** Commit */
            commit: string;
            /** Env */
            env: string;
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "error";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Version */
            version: string;
        };
        /**
         * InstrumentDetailOut
         * @description An instrument and what a valid `/candles` request for it can ask for.
         */
        InstrumentDetailOut: {
            /**
             * Available From
             * @description Open time of the first candle, UTC epoch seconds; null when not known.
             * @example 1502928000
             */
            available_from: number | null;
            /**
             * Available To
             * @description Open time of the newest closed 1m candle, UTC epoch seconds.
             * @example 1790424000
             */
            available_to: number;
            /**
             * Base
             * @description Base asset of a crypto pair; null for stocks.
             * @example BTC
             */
            base: string | null;
            /**
             * Exchange
             * @description Listing exchange of a stock (`NASDAQ`, `NYSE`, `ARCA`, ...); null for crypto.
             * @example null
             */
            exchange: string | null;
            /**
             * Feed
             * @description `spot` (Binance spot) or `iex` (Alpaca IEX: IEX trades only).
             * @example spot
             * @enum {string}
             */
            feed: "spot" | "iex";
            /**
             * Id
             * @description Instrument id, `<market>:<symbol>`.
             * @example crypto:BTCUSDT
             */
            id: string;
            /** @example crypto */
            market: components["schemas"]["Market"];
            /**
             * Max Candles
             * @description Most candles one `/candles` response may hold.
             * @example 50000
             */
            max_candles: number;
            /**
             * Name
             * @description Crypto: `<base>/<quote>`. Stocks: the company or fund name from Alpaca.
             * @example BTC/USDT
             */
            name: string;
            /**
             * Quote
             * @description Quote asset of a crypto pair; null for stocks.
             * @example USDT
             */
            quote: string | null;
            /**
             * Source
             * @example binance
             * @enum {string}
             */
            source: "binance" | "alpaca";
            /**
             * Symbol
             * @description Symbol as the source spells it.
             * @example BTCUSDT
             */
            symbol: string;
            /**
             * Timeframes
             * @example [
             *       "1m",
             *       "5m",
             *       "15m",
             *       "1h",
             *       "4h",
             *       "1d"
             *     ]
             */
            timeframes: components["schemas"]["Timeframe"][];
        };
        /**
         * InstrumentOut
         * @description One instrument of a source's catalog.
         */
        InstrumentOut: {
            /**
             * Base
             * @description Base asset of a crypto pair; null for stocks.
             * @example BTC
             */
            base: string | null;
            /**
             * Exchange
             * @description Listing exchange of a stock (`NASDAQ`, `NYSE`, `ARCA`, ...); null for crypto.
             * @example null
             */
            exchange: string | null;
            /**
             * Feed
             * @description `spot` (Binance spot) or `iex` (Alpaca IEX: IEX trades only).
             * @example spot
             * @enum {string}
             */
            feed: "spot" | "iex";
            /**
             * Id
             * @description Instrument id, `<market>:<symbol>`.
             * @example crypto:BTCUSDT
             */
            id: string;
            /** @example crypto */
            market: components["schemas"]["Market"];
            /**
             * Name
             * @description Crypto: `<base>/<quote>`. Stocks: the company or fund name from Alpaca.
             * @example BTC/USDT
             */
            name: string;
            /**
             * Quote
             * @description Quote asset of a crypto pair; null for stocks.
             * @example USDT
             */
            quote: string | null;
            /**
             * Source
             * @example binance
             * @enum {string}
             */
            source: "binance" | "alpaca";
            /**
             * Symbol
             * @description Symbol as the source spells it.
             * @example BTCUSDT
             */
            symbol: string;
        };
        /** InstrumentSearchOut */
        InstrumentSearchOut: {
            /**
             * Count
             * @description Number of items.
             * @example 1
             */
            count: number;
            /**
             * Items
             * @description Best matches first.
             */
            items: components["schemas"]["InstrumentOut"][];
            /**
             * Unavailable
             * @description Markets left out of this search because their instrument list cannot be loaded right now (the source is down); search again later. Empty normally.
             * @example []
             */
            unavailable: components["schemas"]["Market"][];
        };
        /**
         * Market
         * @enum {string}
         */
        Market: "crypto" | "stock";
        /**
         * Problem
         * @description Error response (RFC 9457). Some problems add members, such as `errors` on 422.
         */
        Problem: {
            /**
             * Detail
             * @example query parameter 'limit': Input should be at most 100
             */
            detail: string;
            /**
             * Status
             * @example 422
             */
            status: number;
            /**
             * Title
             * @example Invalid request
             */
            title: string;
            /**
             * Type
             * @example https://candlestack.tech/problems/validation
             */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /** SourceHealthOut */
        SourceHealthOut: {
            /**
             * Detail
             * @description What failed; null when ok.
             * @example null
             */
            detail: string | null;
            /**
             * Latency Ms
             * @description Duration of the check; null when the source did not answer.
             * @example 84
             */
            latency_ms: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /**
         * SourcesHealthOut
         * @description Reachability of the market data sources, checked at most once a minute.
         */
        SourcesHealthOut: {
            /** Sources */
            sources: {
                [key: string]: components["schemas"]["SourceHealthOut"];
            };
            /**
             * Status
             * @description `ok` when every source is reachable.
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /**
         * Timeframe
         * @description Candle durations; iteration goes from the shortest to the longest.
         * @enum {string}
         */
        Timeframe: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Redis is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    sources_health_api_health_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesHealthOut"];
                };
            };
            /** @description A source is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesHealthOut"];
                };
            };
        };
    };
    candles_api_v1_data_candles_get: {
        parameters: {
            query: {
                /** @description Instrument id, `<market>:<symbol>`. */
                instrument: string;
                timeframe: components["schemas"]["Timeframe"];
                /** @description Start of the period, inclusive: UTC epoch seconds or ISO 8601 (`2024-06-03`, `2024-06-03T13:30:00Z`; without an offset it is UTC). */
                start: number | string;
                /** @description End of the period, exclusive, in the same formats; default now. */
                end?: (number | string) | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandlesOut"];
                };
            };
            /** @description The instrument is not in the catalog (`instrument-not-found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid parameters (`validation`), a period outside the available data (`period-out-of-range`) or more candles than `max_candles` (`too-many-candles`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description More candle and instrument requests from this address than the per-minute limit (`rate-limited`); see `Retry-After`. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The source sent data that failed validation (`source-data-invalid`). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The source is down or our request budget for it is spent (`source-unavailable`); `Retry-After` when waiting helps. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    search_instruments_api_v1_data_instruments_get: {
        parameters: {
            query: {
                /** @description Symbol or name, case-insensitive; separators in symbols are ignored (`btc/usdt` finds `BTCUSDT`, `brkb` finds `BRK.B`). */
                q: string;
                /** @description Only this market. */
                market?: components["schemas"]["Market"] | null;
                /** @description Most items to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentSearchOut"];
                };
            };
            /** @description Invalid parameters (`validation`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The source sent data that failed validation (`source-data-invalid`). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The source is down or our request budget for it is spent (`source-unavailable`); `Retry-After` when waiting helps. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    instrument_detail_api_v1_data_instruments__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Instrument id, `<market>:<symbol>`. */
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentDetailOut"];
                };
            };
            /** @description The instrument is not in the catalog (`instrument-not-found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Malformed instrument id (`validation`). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description More candle and instrument requests from this address than the per-minute limit (`rate-limited`); see `Retry-After`. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The source sent data that failed validation (`source-data-invalid`). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description The source is down or our request budget for it is spent (`source-unavailable`); `Retry-After` when waiting helps. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
